name: Staging Build and Deploy

on:
  push:
    branches:
      - staging

jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1

      - name: Install and Build 🔧 # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
        run: |
          export VUE_APP_BACKEND_IP="$API_URL"
          npm install
          npm run build
          cp ./dist/index.html ./dist/404.html
        env:
          API_URL: ${{secrets.VUE_APP_BACKEND_IP_STAGGING}}
