name: Development_Deploy

on:
  push:
    branches: [ development ]
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1

      - name: Install and Build 🔧 # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
        run: |
          export VUE_APP_BACKEND_IP="$API_URL"
          export VUE_APP_NOTIFICATION_SERVER_IP="$NOTIFICATION_SERVER_IP"
        env:
          API_URL: ${{secrets.VUE_APP_BACKEND_IP_DEV}}
          NOTIFICATION_SERVER_IP:  ${{secrets.VUE_APP_NOTIFICATION_SERVER_IP}}
          
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEV_HOST }}
          username: ${{ secrets.DEV_USERNAME }}
          password: ${{ secrets.DEV_PASSWORD }}
          script: |
                  export VUE_APP_BACKEND_IP=${{secrets.VUE_APP_BACKEND_IP_DEV}}
                  export VUE_APP_NOTIFICATION_SERVER_IP= ${{secrets.VUE_APP_NOTIFICATION_SERVER_IP}}
                  ${{ secrets.SCRIPT }}
        
