name: Development_Deploy

on:
  push:
    branches: [ development ]
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Build the tagged Docker image
      run: |
          export VUE_APP_BACKEND_IP="$API_URL"
          export VUE_APP_NOTIFICATION_SERVER_IP="$NOTIFICATION_SERVER_IP"
        env:
          API_URL: ${{secrets.VUE_APP_BACKEND_IP_STAGGING}}
          NOTIFICATION_SERVER_IP:  ${{secrets.VUE_APP_NOTIFICATION_SERVER_IP}}
          
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.STAGING_HOST }}
        username: ${{ secrets.STAGING_USERNAME }}
        password: ${{ secrets.STAGING_PASSWORD }}
        script: ${{ secrets.STAGING_PASSWORD }}
